# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 3.3
matrix:
  include:
    - python: 2.7
      env: TESTMODE=full
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - mkdir builds
  - pushd builds
  - pip install nose
  - pip install numpy
  - pip install Cython
  # mpmath for scipy.special tests
  - pip install mpmath
  # For Python 2.6 we also need argparse
  - pip install argparse
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - if [ "${TESTMODE}" == "full" ]; then sudo pip install coverage; fi
  - if [ "${TESTMODE}" == "full" ]; then sudo pip install coveralls; fi
  - python -V
  - popd
script:
  - if [ "${TESTMODE}" == "full" ]; then coverage run --rcfile=.travis_coveragerc runtests.py -g -m $TESTMODE --coverage; else $PYTHON runtests.py -g -m $TESTMODE; fi
env:
  - TESTMODE=fast
notifications:
  # Perhaps we should have status emails sent to the mailing list, but
  # let's wait to see what people think before turning that on.
  email: false
after_success:
    - if [ "${TESTMODE}" == "full" ]; then coveralls; fi
